### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by unmellow** [Crazy-Hand-Project/Crazy-Hand#7]
whenever I try to open my melee iso this happens also I can't copy the output so here's photos
I'm using jdk10 I tried it with 8 but the output looked the same

![huh](https://user-images.githubusercontent.com/30985587/46708190-6cfc9800-cc0b-11e8-91c7-d489c367160a.png)
![huh2](https://user-images.githubusercontent.com/30985587/46708191-6cfc9800-cc0b-11e8-9249-7fcc836c0cf6.png)
![huh3](https://user-images.githubusercontent.com/30985587/46708193-6cfc9800-cc0b-11e8-8e1e-8e4edb086d63.png)
![huh4](https://user-images.githubusercontent.com/30985587/46708194-6d952e80-cc0b-11e8-9943-ed796fd86143.png)

**Comment by unmellow** [comment]
my computer is wierd but i think i was able to copy it YEAH

..[melton@unmellow-pc] - [~] - [Tue Oct 09, 09:26]
..[$] <()> java -jar ./APP/Crazy\ Hand\ v1.31/Crazy\ Hand\ v1.31.jar
advfsm:true
4564688
ItCo.dat
PlBo.dat
PlCa.dat
PlCaAJ.dat
PlCh.dat
PlCl.dat
PlCo.dat
PlDk.dat
PlDr.dat
PlFc.dat
PlFe.dat
PlFx.dat
PlGk.dat
PlGl.dat
PlGn.dat
PlGw.dat
PlKb.dat
PlKp.dat
PlLg.dat
PlLk.dat
PlMh.dat
PlMr.dat
PlMs.dat
PlMt.dat
PlNn.dat
PlNs.dat
PlPc.dat
PlPe.dat
PlPk.dat
PlPp.dat
PlPr.dat
PlSb.dat
PlSk.dat
PlSs.dat
PlYs.dat
PlZd.dat
PlKp.dat
File is 0x2fd00 bytes in length.
false
java.io.FileNotFoundException: def/102/PlKp.dat (No such file or directory)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
        at java.base/java.io.Ra

**Comment by unmellow** [comment]
after an unrelated reinstall of manjaro this happens
![bug](https://user-images.githubusercontent.com/30985587/48165095-83e9e500-e2b2-11e8-8cdd-0b635eb164af.png)
![bug 2](https://user-images.githubusercontent.com/30985587/48165096-83e9e500-e2b2-11e8-94d9-18e2c4ae6f16.png)
![bug 3](https://user-images.githubusercontent.com/30985587/48165097-84827b80-e2b2-11e8-96c3-ab8fde1403e8.png)
